module.exports = {
  projects: [
    '<rootDir>/apps/github-user-search',
    '<rootDir>/libs/material',
    '<rootDir>/libs/model',
    '<rootDir>/libs/feature/lazy/users',
    '<rootDir>/libs/feature/api/search',
    '<rootDir>/libs/utils/func',
    '<rootDir>/libs/feature/api/users',
    '<rootDir>/libs/feature/lazy/search',
    '<rootDir>/libs/feature/shared/search-results-page',
    '<rootDir>/libs/ui-kit/toolbar',
    '<rootDir>/libs/shared/classes',
    '<rootDir>/libs/ui-kit/list',
    '<rootDir>/libs/ui-kit/list-filter',
    '<rootDir>/libs/ui-kit/search-form',
    '<rootDir>/libs/shared/directives',
    '<rootDir>/libs/feature/shared/search-result-item-details',
    '<rootDir>/libs/utils/http-interceptor',
    '<rootDir>/libs/ui-kit/loading-progress',
    '<rootDir>/libs/shared/http-interceptors',
    '<rootDir>/libs/shared/styles',
    '<rootDir>/libs/feature/api/repositories',
    '<rootDir>/libs/feature/lazy/repositories',
  ],
};
